# Streamlit Secrets Configuration
# Copy this file to .streamlit/secrets.toml for local development
# For Streamlit Cloud, add these as secrets in the dashboard

# Gemini API Configuration
GEMINI_API_KEY = "AIzaSyCUqOEyJ4mVyhQ0CvH1_aaBL7p4wQLFpLo"

# Optional: Customize default values
# BIRTH_CHART = "Sun in Libra, Ascendant in Capricorn"
# DISC_PROFILE = "High C, low I"
